# Generated by Django 4.0.5 on 2022-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idprod',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
    ]
