# Generated by Django 4.0.5 on 2022-06-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='xd', max_length=50, verbose_name='Direccion'),
            preserve_default=False,
        ),
    ]
